### ISSUE TITLE
Unauthorized access

### ISSUE THREAD

**Issue by Gabvoir** [Thibautg16/XeeAppEedomus#2]
Bonjour,
On obtient l'erreur suivant quand 2 périphérique Xee sont créé afin de se connecter à 2 comptes différents :
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<root><error>authorization_error</error>
<error_description>Unauthorized access</error_description>
</root>
```
Il semblerait que le "attached_controller_id" soit identique pour ces 2 périphériques.
Si j'ai bien compris le fonctionnement d'eedomus, c'est cet id qui est maître des paramètres qu'on veut stocker. Si cet id ne change pas pas entre les 2 périphériques, les paramètres stocké sont fusionné.

**Comment by Gabvoir** [comment]
le "attached_controller_id" n'a rien à faire puisque c'est l'id de l'eedomus.

**Comment by Thibautg16** [comment]
Bonjour,
C'est corrigé avec la version 5.4 ;)
